services:
  flask-backend:
    image: samihosni/backend-flask:latest
    container_name: flask-backend-app
    ports:
      - "5000:5000"
    depends_on:
      - ollama
    networks:
      - app-network
    environment:
      - OLLAMA_HOST=http://localhost:11434
    

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    networks:
      - app-network
    volumes:
      - ollama-data:/root/.ollama   # Persist Ollama models and settings
    

  react-frontend:
    image: samihosni/frontend-react:latest
    container_name: react-frontend
    ports:
      - "3000:80"
    depends_on:
      - flask-backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  ollama-data:
